name: Next.js Pipelines

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  dep:
    name: dependecies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: | 
          echo "Running installing dependecies ... "
          npm install