name: Next.js Pipelines

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  e2e-tests:
    name: e2e-tests
    environment: preview
    runs-on: ubuntu-latest
    container: cypress/browsers:node14.17.6-chrome100-ff98
    env:
      NEXT_PUBLIC_CLOUDINARY_NAME: ${{secrets.NEXT_PUBLIC_CLOUDINARY_NAME}}
      NEXT_PUBLIC_CLOUDINARY_API_KEY: ${{secrets.NEXT_PUBLIC_CLOUDINARY_API_KEY}}
      NEXT_PUBLIC_CLOUDINARY_API_SECRET: ${{secrets.NEXT_PUBLIC_CLOUDINARY_API_SECRET}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run tests
        uses: cypress-io/github-action@v4
        with:
          browser: chrome
          start: npx next dev
          wait-on: "http://localhost:3000"

  unit-tests:
    name: unit-tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          echo "Running installing dependecies ... "
          npm install
      - name: Run tests
        run: |
          echo "Running tests ... "
          npm run test
