name: Next.js Pipelines

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  setup:
    name: setup
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: | 
          echo "Running installing dependecies ... "
          npm install

  lint:
    name: lint
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: | 
          echo "Running installing dependecies ... "
          npm install

      - name: Run linting
        run: |
          echo "Running linting ... "
          npm run lint